version: '2'
services:
  web2:
    image: dyalog/miserver
    stdin_open: true
    volumes:
    - /DockerVolumes/MiServer/DrA:/MiServer/MS3/DrA
    tty: true
    labels:
      io.rancher.container.pull_image: always
  DrA-Sender:
    image: registry.dyalog.com:5000/dyalog/drachecker:latest
    environment:
      MAILTO: brian@dyalog.com mbaas@dyalog.com
      MAILFROM: MiServer DrA <admin@dyalog.com>
      MAILSUBJECT: '[MiServer] DrA Error captured'
    stdin_open: true
    volumes:
    - /DockerVolumes/MiServer/DrA:/DrA
    tty: true
    labels:
      io.rancher.container.pull_image: always