version: '2'
services:
  web:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: ''
      port_rules:
      - hostname: ''
        path: ''
        protocol: http
        service: web
        source_port: 80
        target_port: 8080
    load_balancer_config:
      haproxy_config: {}
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
