:class linkAdvanced: MiPageSample
⍝ Control:: _html.link
⍝ Description:: Embed raw image data in the page itself

    ∇ Compose
      :Access public
     
      duck←'AAABAAEAEBAAAAAAAABoBQAAFgAAACgAAAAQAAAAIAAAAAEACAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAM834ABu/6gDJ8f0AXdn3ADjS9QBY4PoAK7bhAESlyQAhyP'
      duck,←'MARNP4AEbT+AAXtuIALcvzADHH8ACKrLkAGLvoAB+24gDHy8wAFcHxABy+6AAXv/QAHr/rADXR/AAYw/cAIr/rAKbw/AAhy/QARNb5AEjS9gAYq90AFq7dABaz2gAfq9QAGq7d'
      duck,←'ACjM9wAtyvEAdt71ABa48gBV1/wAV7PQABq+6QDf4N4AG7/sABzA7wAXyPUA0PX5AB3F9QA4QNAAF6zYAMzP6wAojuEAjeb7AGq60wAYsd4ASdj3ABa14QBs4/wAGrbkABqy8w'
      duck,←'AYxe0AKLjhAB3C7QBa3/oAncTwANj1+gC86vUAIGSBAJjCxwAatN8AGa/rADnG5wAcueUAnen8ABbB9ABZ3fUAONH2ACG68QAtdeAASKLEAB7C9wAin8UA0NTPABar1wBB1fkA'
      duck,←'FbDdADeE4ADv6uwATdX5AMPIxwAZteMAxsXHAB+12gDIxccAfd74AHrj/gAVw/IAXtbzAOLj4QA80PQAXt32AKrr+gBh3PwAIcXvANDS0wBQy+UAJsr1ADdQ1gAypcYAbrblAB'
      duck,←'m45AAYvOcAFsDqAB636gDI8foAF8DzAEDJ6QDR6/EAMTnIAM7MywBc2vcAFivDAIrg9gAhxfAAHcnzABaq1gAfx/YARs74AC++5AAWp98AR67PABav3AAUrOUAFrHiABux2QBk'
      duck,←'o7cAFbnoAC7I+QAgstwAdHTeAFTb+wBY2vgAHMDrAKfs9gAgxO4AGqTOAILF1AAcKsoAQNf5AEXT9gBq3fgAI8v6ANr3+wAas+AAQq3xAIGxvQBP1/kAMc76ABrC8gCE5PsAGJ'
      duck,←'XqAITn+wBD0foAk9/1ALPw+gBu3PYAtfD6AJDq+wCNlNMAduH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
      duck,←'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
      duck,←'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
      duck,←'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqd1tdWVJiAAAAAAAAAB'
      duck,←'IPh08Igig1RGgAAAAAV5tskX0iNjoQKStHdQAAAJIHXIqGRW4UPjwbF14AAABpgCAxUyKZSI6QagU3AABCdD1aEZmDVThvFmcBlAAAoyQOexYCcAwfhYgsCRwAAHpUjI0KYw1x'
      duck,←'gYQmc3xkAACPBjl4C1h/RjsVI0yVAAAAAKk0n1+hllAYlzNObQAAAAAASaemLiVKIROgeZN2qAAAAAAAAABhUUNNnlZrMIsAAAAAAAAAHRkeYC2JmkAyAAAAAAAAAKVqL36dok'
      duck,←'sAAAAAAAAAAAByBJwnZj8DAAAAAAAAAAAAAJhlGqRBAAAAAPgPAADgBwAAgAMAAIADAACAAwAAAAMAAAADAAAAAwAAAAcAAIAHAADAAQAA/AEAAPwBAAD8BwAA/AcAAP4PAAA='
     
      'href="../Data/apple.ico"' 'rel="icon"' 'type="image/x-icon"'Add _.link
      ('href="data:image/x-icon;base64,',duck,'"')'rel="icon"' 'type="image/x-icon"'Add _.link
     
      Add _.title'← LOOK HERE'
     
      (('href'_Request.Page)('target' '_blank')Add _.a).Add _.p'Click here to open this page in a separate tab or window'
      Add _.p'Most browsers support embedded raw image data.'
      Add _.p'In this case, your browser''s tab or window should show a rubber duck icon.'
      Add _.p'If you are using Internet Explorer, you will instead see a red apple.'
    ∇


:endclass